/*
 * Properties.h
 *
 *  Created on: 31 juil. 2015
 *      Author: horfee
 */

#ifndef PROPERTIES_H_
#define PROPERTIES_H_
#include <termios.h>


#define	PROPERTY_RECEIVING_PIN		"RECEIVING_PIN"
#define	PROPERTY_TRANSMITTING_PIN	"TRANSMITTING_PIN"
#define PROPERTY_CURRENT_MODE		"MODE"
#define PROPERTY_ACCESS_POINT_PASS	"AP_PWD"
#define PROPERTY_WEBSERVER_PORT		"WEB_PORT"
#define PROPERTY_WEBSERVER_ADDR		"WEB_ADDR"
#define PROPERTY_WEBSERVER_ROOT		"WEB_ROOT"
#define PROPERTY_PASSWORD			"PASSWORD"
#define PROPERTY_LOCALE				"LOCALE"
#define PROPERTY_SIM800RESET_PIN	"SIM800_RESET_PIN"
#define PROPERTY_SIM800STREAM		"SIM800_STREAM"
#define PROPERTY_SIM800BAUDRATE		"SIM800_BAUDRATE"

#ifdef WIRINGPI
#define DEFAULT_VALUE_RECEIVING_PIN		4
#define DEFAULT_VALUE_TRANSMITTING_PIN	5
#else
#define DEFAULT_VALUE_RECEIVING_PIN		23
#define DEFAULT_VALUE_TRANSMITTING_PIN	24
#endif
#define DEFAULT_VALUE_ACCESS_POINT_PASS	"password"
#define DEFAULT_VALUE_WEBSERVER_PORT	8080
#define DEFAULT_VALUE_WEBSERVER_ADDR	"*"
#define DEFAULT_VALUE_WEBSERVER_ROOT	"./"
#define DEFAULT_VALUE_PASSWORD			"81dc9bdb52d04dc20036dbd8313ed055"		// MD5 of 1234
#define DEFAULT_VALUE_LOCALE			"en_US"
#ifdef WIRINGPI
#define DEFAULT_VALUE_SIM800RESET_PIN	1
#else
#define DEFAULT_VALUE_SIM800RESET_PIN	18
#endif
#define DEFAULT_VALUE_SIM800STREAM		"/dev/ttyS0"

#ifdef WIRINGPI
#define DEFAULT_VALUE_SIM800BAUDRATE	B115200
#else
#define DEFAULT_VALUE_SIM800BAUDRATE	115200
#endif

#define DEFAULT_VALUE_CURRENT_MODE		"Inactive"

#define PROPERTY_RECEIVING_PIN_DESCRIPTION		"Receiving pin number as WiringPI number"
#define PROPERTY_TRANSMITTING_PIN_DESCRIPTION	"Transmitting pin number as WiringPI number"
#define PROPERTY_ACCESS_POINT_PASS_DESCRIPTION	"Access Point Password"
#define PROPERTY_CURRENT_MODE_DESCRIPTION		"Current mode"
#define PROPERTY_WEBSERVER_PORT_DESCRIPTION		"Web Server listening Port"
#define PROPERTY_WEBSERVER_ADDR_DESCRIPTION		"Web Server listening address"
#define PROPERTY_WEBSERVER_ROOT_DESCRIPTION		"Web server root folder"
#define PROPERTY_PASSWORD_DESCRIPTION			"Password to access to the alarm functions"
#define PROPERTY_LOCALE_DESCRIPTION				"Locale used for messaging"
#define PROPERTY_SIM800RESET_PIN_DESCRIPTION	"GSM Module Reset pin number as WiringPI number"
#define PROPERTY_SIM800STREAM_DESCRIPTION		"GSM Module serial file stream"
#define PROPERTY_SIM800BAUDRATE_DESCRIPTION		"GSM Module serial file stream baud rate"

#endif /* PROPERTIES_H_ */

